// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GuardType } from "./GuardType";

export interface GiftMessage { uid: bigint, uname: string, guard: GuardType, gift_id: bigint, gift_name: string, gift_num: number, }