// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Room { roomid: string, uid: string, content: string, ctime: string, status: string, uname: string, }